export const RETAIL_CHANNELS = [
  { value: "accountant", label: "Accountant" },
  { value: "auto-services", label: "Auto Services / Car Wash" },
  { value: "bakery", label: "Bakery" },
  { value: "bookstore", label: "Bookstore" },
  { value: "childcare", label: "Childcare / Daycare" },
  { value: "coffee-shop", label: "Coffee Shop" },
  { value: "convenience-store", label: "Convenience Store" },
  { value: "dental-office", label: "Dental Office" },
  { value: "doctors-office", label: "Doctor's Office" },
  { value: "dry-cleaner", label: "Dry Cleaner" },
  { value: "entertainment-venue", label: "Entertainment Venue" },
  { value: "fashion-retail", label: "Fashion Retail" },
  { value: "fast-casual-restaurant", label: "Fast Casual Restaurant" },
  { value: "florist", label: "Florist" },
  { value: "full-service-restaurant-bar", label: "Full-Service Restaurant / Bar" },
  { value: "gym-fitness", label: "Gym / Fitness Studio" },
  { value: "hardware", label: "Hardware" },
  { value: "home-goods", label: "Home Goods" },
  { value: "hotel", label: "Hotel" },
  { value: "insurance-agency", label: "Insurance Agency" },
  { value: "jewelry-store", label: "Jewelry Store" },
  { value: "legal-office", label: "Legal Office" },
  { value: "liquor-store", label: "Liquor Store" },
  { value: "office-supplies", label: "Office Supplies" },
  { value: "optometrist", label: "Optometrist / Eye Care" },
  { value: "pet-care-store", label: "Pet Care / Store" },
  { value: "pharmacy", label: "Pharmacy" },
  { value: "real-estate", label: "Real Estate" },
  { value: "salon-barber", label: "Salon / Barber Shop" },
  { value: "school", label: "School" },
  { value: "shipping-delivery", label: "Shipping / Delivery" },
  { value: "spa", label: "Spa" },
  { value: "supermarket", label: "Supermarket" },
  { value: "tattoo-parlor", label: "Tattoo Parlor" },
  { value: "veterinarian", label: "Veterinarian" },
  { value: "other", label: "Other (miscellaneous)" },
] as const;

export const RETAIL_CHANNEL_VALUES = RETAIL_CHANNELS.map(ch => ch.value);

