// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fimmfxizfxlenzvmfudo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpbW1meGl6ZnhsZW56dm1mdWRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3NjcxMzAsImV4cCI6MjA3NTM0MzEzMH0.U6vD8uMQXLMpvpCUGQvAUdQoHpzCTUJGy_FvP9DSDMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});